<?php


namespace App\Repositories;


use App\Portfolio;

class PortfolioRepository extends Repository
{
    public function __construct(Portfolio $portfolio)
    {
        $this->model = $portfolio;
    }

    public function one($alias, $atr = [])
    {
        $portfolio = parent::one($alias, $atr); // TODO: Change the autogenerated stub

        if ($portfolio->img) {
            $portfolio->img = json_decode($portfolio->img);
        }

        return $portfolio;
    }

}
